# DHNL Continuous Integration
#

stages:
  - build
  - package
  - run
  - test

build_code:
  stage: build
  image: atlas/analysisbase:21.2.90
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  before_script:
    - source /home/atlas/release_setup.sh
  script:
    - mkdir build
    - cd build
    - cmake ../CMakeLists.txt
    - cmake --build .
  after_script:
    - source "${AnalysisBase_PLATFORM}/setup.sh"
  # only:
  #   changes:
  #     - src
  artifacts:
    paths:
      - build
    expire_in: 1 day
